env:
  es2021: true
  node: true
extends: airbnb-base
parseOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extensions:
  - error
  - ignorePackages
  - js: always
  